### ISSUE TITLE
 Calculator android build failed

### ISSUE THREAD

**Issue by juan-reynoso** [part-cw/lambdanative#209]
Hello I am reading the Getting Started, so  in the  **Step 4: Start the build**    I got an error.
Could you give me a tip? or  What can I do?.

O.S.:  Debian/GNU Linux

This my SETUP info:                                                                                                 
ANDROIDSDK=`find /usr/local/tools_r25.2.5-linux/  -maxdepth 0 -print 2> /dev/null | tail -n 1`                                                       
ANDROIDNDK=`find /usr/local/android-ndk-*  -maxdepth 0 -print  2> /dev/null| tail -n 1`                                                                                                                                               
ANDROIDAPI=27  

Build:
./configure Calculator android debug verbose; make clean; make

This is the message:

BUILD FAILED
/usr/local/tools_r25.2.5-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/usr/local/tools_r25.2.5-linux/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/usr/local/tools_r25.2.5-linux/build-tools/20.0.0/aapt" (in directory "/home/myuser/.lambdanative/tmp_build"): error=2, No existe el fichero o el directorio
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:591)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:630)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
        at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at java.base/java.util.Vector.forEach(Vector.java:1387)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at java.base/java.util.Vector.forEach(Vector.java:1387)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:834)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 49 more

Total time: 4 seconds
ERROR: failed with exit code 1
BUILD FAILED
make: *** [Makefile:2: all] Error 1

**Comment by mgorges** [comment]
It says in there for `/usr/local/tools_r25.2.5-linux/build-tools/20.0.0/aapt` **no such file or directory**, which is the android asset packaging tool. Are your SDK-tools complete?

**Comment by mgorges** [comment]
If the file exists, check if you are missing a dynamically linked library for it, you can do so with `ldd /usr/local/tools_r25.2.5-linux/build-tools/20.0.0/aapt`. 

If this is the case, try adding some of them, such as `apt-get install libncurses5:i386 libstdc++6:i386 zlib1g:i386` - maybe also "libncurses5:i386"

**Comment by juan-reynoso** [comment]
I have installed the packages, now I have :

.
.
.
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
    [javac] Compiling 3 source files to /home/myuser/.lambdanative/tmp_build/bin/classes
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.
BUILD FAILED
/usr/local/tools_r25.2.5-linux/tools/ant/build.xml:716: The following error occurred while executing this line:
/usr/local/tools_r25.2.5-linux/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.
Total time: 3 seconds
ERROR: failed with exit code 1
BUILD FAILED - configure with verbose option for more information
make: *** [Makefile:2: all] Error 1

**Comment by juan-reynoso** [comment]
My java version:

~/src/lisp/lambdanative$ java -version

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)

Is fine my java version?
I get information about java and debian here:
https://wiki.debian.org/Java

**Comment by mgorges** [comment]
Your issue might be related to [issue 195](https://github.com/part-cw/lambdanative/issues/195), whereby Java 9 or 10 have problems, as Java 5+6 support was dropped in Java 9. Try a Java 8 JDK and see if that temporarily solves your issue.

**Comment by juan-reynoso** [comment]
I got the Calculator-1.0-android.apk file, so I try to install it on my mobile  but the **package installer** show me an error called:
**Parse error:
There was a problem while parsing the package.**

 Unknown sources  is enabled on my mobile

**Comment by mgorges** [comment]
This is a rather unspecific error description so hard to debug - can you provide us with a link to the file to have a look? Also what mobile device (Android version) are you using and could you list the content of the APK file below here?

**Comment by juan-reynoso** [comment]
File:
https://www.dropbox.com/s/d46ggnm2eotq5dl/Calculator-1.0-android.apk

Android version:
Android 5.1;  Build number  LPBS23.13-56-2

**Comment by mgorges** [comment]
I get the following issue, using an AVDbased on Android 5.0.1, ARM (armeabi-v7a) processor: 

     5323m:platform-tools mgorges$ ./adb install ~/Downloads/Calculator-1.0-android.apk 
     /Users/mgorges/Downloads/Calculator-1.0-android.apk: 1 file pushed. 6.0 MB/s (3551542 bytes in 0.564s)
     	pkg: /data/local/tmp/Calculator-1.0-android.apk
     Failure [INSTALL_FAILED_OLDER_SDK]

--> You earlier stated to target Android 8.1 (API level 27), so that won't work with a 5.0.1 or 5.1 device.

**Comment by juan-reynoso** [comment]
Thanks a lot, I read the new **https://github.com/part-cw/lambdanative/wiki/Getting-Started** 
I have a fresh install and it works good.
file:
https://www.dropbox.com/s/gg0rd651rl8idqp/Calculator-1.0-android-5.1.apk
I installed the  Calculator-1.0-android.apk on my mobile Android 5.1

awesome!
