### ISSUE TITLE
Redirect log messages from Java into LambdaNative log file

### ISSUE THREAD

**Issue by mgorges** [part-cw/lambdanative#358]
Question: How would I redirect (log or log alike) messages from Java code to the LN logfile?

The exception I ran into with simply requesting CAMERA permissions (after those being granted):

    Error android.os.FileUriExposedException: file:///sdcard/front/_camera_tmp.jpg exposed beyond app through ClipData.Item.getUri()
    android.os.FileUriExposedException: file:///sdcard/front/_camera_tmp.jpg exposed beyond app through ClipData.Item.getUri()
            at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
            at android.net.Uri.checkFileUriExposed(Uri.java:2356)
            at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
            at android.content.Intent.prepareToLeaveProcess(Intent.java:9850)
            at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
            at android.app.Activity.startActivityForResult(Activity.java:4501)
            at android.app.Activity.startActivityForResult(Activity.java:4459)
            at net.softeyes.front.front.startCamera(front.java:371)
            at net.softeyes.front.myRenderer.nativeEvent(Native Method)
            at net.softeyes.front.myRenderer.pointerEvent(front.java:548)
            at net.softeyes.front.xGLSurfaceView$2.run(front.java:477)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

_Originally posted by @0-8-15 in https://github.com/part-cw/lambdanative/pull/256#issuecomment-527558593_

**Comment by mgorges** [comment]
This might be relevant: https://stackoverflow.com/questions/19565685/saving-logcat-to-a-text-file-in-android-device
