### ISSUE TITLE
no SDK anymore ...

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#440]
Google has disabled direct SDK download, so there is no option to get the android-sdk-XXX any more. I can install an SDK via sdkmanager, The SDK is placed under  android-ndk-r25c just as it was in the old SDK, but that does not result in a usable SDK:

```
ANDROIDSDK=/home/lambdanative/android-ndk-r25c
ANDROIDNDK=/home/lambdanative/android-ndk-r25c

```

```
$ make
=== using profile your profile name here [/home/lambdanative/lambdanative/PROFILE]..
=== configured to build Calculator version 1.0 for android on linux in normal mode

modules requested: config eventloop ln_core ln_glcore ln_glgui
modules identified:  config eventloop ln_core ln_glcore clipboard ln_glgui
ERROR: failed on file /home/lambdanative/android-ndk-r25c/platforms/android-3/arch-arm64
BUILD FAILED
make: *** [Makefile:2: all] Fehler 1

```

I can still use android-ndk-r21d  + android-sdk-25.2.5, but the resulting APKs are not accepted by google any more.

Any idea how I could build ndroid APKs with SDK 31 nowadays?

**Comment by zwieblum** [comment]
Additional note: android-ndk-r21e is the last usable NDK version, anyting newer fails when running "configure XXXXX android":
```
=== using profile The ingeniouse profile of XXXXX [/....../lambdanative/PROFILE]..
=== configured to build XXXXX version 1.01 for android on linux in normal mode

ERROR: failed on file /....../android-ndk-r22b//platforms/android-3/arch-arm64
BUILD FAILED - configure with verbose option for more information
make: *** [Makefile:2: all] Fehler 1
```

**Comment by mgorges** [comment]
> Any idea how I could build ndroid APKs with SDK 31 nowadays?

Commit f252634 should have made the changes to do that. At least it worked on the devices and simulator when we tested it earlier this year but maybe Google changed something in the meantime?

**Comment by mgorges** [comment]
Quick update on how far I have gotten: I followed the instructions at https://github.com/part-cw/lambdanative/wiki/Getting-Started#android-macos-or-linux and downloaded first the command line tools (10406996) from https://developer.android.com/studio, which I put into `/usr/local/android-sdk-macosx/`, which places the sdkmanager at `/usr/local/android-sdk-macosx/cmdline-tools/bin/sdkmanager`. Next, I got the LTS version (r25c) of the NDK from https://developer.android.com/ndk/downloads#lts-downloads and dragged the application from the DMG to `/Applications/AndroidNDK9519653.app`. 

I then run `./sdkmanager` but get a complaint that `'com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0'`, which means I have Java 8 and this thing wants Java 17 or newer is needed. Thus I now need a newer OpenJDK, but https://jdk.java.net/17/ is whiny so I need to explore the proper LTS version before continuing - will look more into this tomorrow, sorry.

**Comment by mgorges** [comment]
Work in progress for [targets/android/_host_macosx#L41](https://github.com/part-cw/lambdanative/blob/master/targets/android/_host_macosx#L41)
```
SYS_PLATFORM_VARIANT="-api${SYS_ANDROIDAPI}"
if [ "X$ANDROIDARCH" = "Xarm64" ]; then
  android_cross=`ls -1d $ANDROIDNDK/toolchains/llvm/prebuilt/*/bin/aarch64*$SYS_ANDROIDAPI-clang | head -n 1`
else
  android_cross=`ls -1d $ANDROIDNDK/toolchains/llvm/prebuilt/*/bin/${ANDROIDARCH}*$SYS_ANDROIDAPI-clang | head -n 1`
fi
android_chainpath=`dirname "$android_cross"`/
SYS_CC=$android_cross" $SYS_DEBUGFLAG -fPIC -DANDROID $cflag_additions"
SYS_CXX=$android_cross"++ $SYS_DEBUGFLAG -fPIC -DANDROID $cflag_additions"
SYS_CPP=$android_cross" -E"
SYS_AR=$android_chainpath"llvm-ar"
SYS_AS=$android_chainpath"llvm-as"
SYS_NM=$android_chainpath"llvm-nm"
SYS_LD=$android_chainpath"lld"
SYS_RANLIB=$android_chainpath"llvm-ranlib"
SYS_STRIP=$android_chainpath"llvm-strip"
SYS_OBJCOPY=$android_chainpath"llvm-objcopy"
SYS_OBJDUMP=$android_chainpath"llvm-objdump"
SYS_READELF=$android_chainpath"llvm-readelf"
```

**Comment by mgorges** [comment]
Before I commit things related to this, could you test this, please?

**Comment by zwieblum** [comment]
Aehm ... test what? I don't have  MacOS, I'm on Linux :)

**Comment by mgorges** [comment]
The content for Linux should be similar if not identical; I'll need to setup a VM to test this myself.

**Comment by zwieblum** [comment]
Any news on this - or how I could test?

**Comment by mgorges** [comment]
Try the work-in progress comment I made above for macOS in [targets/android/_host_linux](https://github.com/part-cw/lambdanative/blob/master/targets/android/_host_linux) on Linux, as that might be the start to make progress. My capacity to set up new Linux VMs, android SDKs, etc is unfortunately limited at the moment and will remain so for at least another week. Sorry.

**Comment by mgorges** [comment]
Tested this on Gentoo Linux with android-ndk-r26b-linux.zip and commandlinetools-linux-10406996_latest.zip for DemoRedSquare targeting ANDROID_API=21, and it compiles an application. I don't have an Android device to test with, but it makes the file. We may have to bump JAVAVERSION=1.7 (from 1.6) as my version of ant is complaining and could potentially also drop clang from the check-tools for android requirements as it ships with the NDK? If you could confirm this works I'll figure out how to make it switchable to continue to support legacy versions, or we just drop those.

**Comment by kiatoa** [comment]
I'm trying to follow these steps to make apk packages also. From reading the above it seemed that doing a git pull would get me the needed changes but that did not change anything. I'll test and instructions for Linux posted here. Thanks.

**Comment by mgorges** [comment]
I have not committed the two changes I made locally and tested on macOS and Gentoo Linux, as I don't have an Android device. It builds, but I can't guarantee it runs, which is why I didn't commit it yet.

**Comment by kiatoa** [comment]
can you put the changes on a branch or something to make them accessible for me to try? Alternatively attach the apk file here and I can test it on an android device.

**Comment by zwieblum** [comment]
Would like to test it, too :)

**Comment by mgorges** [comment]
I don't understand why this can't be tested manually, so I have committed it as a51e212; it should be backwards compatible but this might break things!

**Comment by zwieblum** [comment]
Thank you verry much! I can build DemoCube, now, just signing the apk fails (looks like I need a new key).

For all interested, this is how I did the installation:, it differs from gettingstarted in the wiki. Go to a directory where you'd like lambdanative to reside and do:
```
LAMBDANATIVE=$(realpath ./lambdanative)
SDK=$(realpath ./)/android-sdk-linux

# n case you want a full rebuild:
#rm -Rf lambdanative ~/.cache/lambdanative ~/.lambdanative
#git clone --depth=1 https://github.com/part-cw/lambdanative.git

rm -Rf $SDK
mkdir -p $SDK
cd $SDK

wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
unzip commandlinetools-linux-10406996_latest.zip
mkdir latest
mv cmdline-tools/* latest
mv latest cmdline-tools
cd cmdline-tools/latest/bin
./sdkmanager "platform-tools"
./sdkmanager "build-tools;28.0.2"
#./sdkmanager "ndk;26.1.10909125"
./sdkmanager "ndk;25.2.9519653"
./sdkmanager "extras;android;m2repository"
./sdkmanager "platforms;android-23"

which jarsigner || echo jarfinder needed, install openjdk-17-jdk-headless or simillar.

cd $LAMBDANATIVE
sed 's#^\(ANDROIDSDK\)=.*$#\1='$SDK'#' -i SETUP
sed 's#^\(ANDROIDNDK\)=.*$#\1='$(find $SDK/ndk/* -maxdepth 0 -type d | sort | tail -n1)'#' -i SETUP
sed 's#^\(ANDROIDAPI\)=.*$#\1=23#' -i SETUP
sed 's#^\(JAVAVERSION\)=.*$#\1=1.8#' -i SETUP

V=$(cat VERSION |grep '^#'|tail -n 1|tr ':' ' '|awk '{print $2}')
sed 's/^[0-9].*$/'$V'/' -i VERSION
sed 's/libgambc/libgambit/g' -i modules/config/LIBRARIES

sed 's:^|#:|#\n(glgui-timings-at-sec! 0.0):' -i lambdanative/apps/DemoCube/main.scm
./configure DemoCube verbose android
make
```

No I'll check I can get the app signed and uploaded to a real device.

**Comment by mgorges** [comment]
Thanks for adding this - it could be helpful to update the documentation to outline the new process based on my experience above and your process here. Regarding the signing piece, if there is not android keystore we make one in [targets/android/build-binary#L415](https://github.com/part-cw/lambdanative/blob/master/targets/android/build-binary#L415). If you provide the errors you get, I'd be happy to try and troubleshoot it.

**Comment by kiatoa** [comment]
The script to set up android + lambdanative worked for me. Very nice, thanks!

It took me a couple tries and a fair amount of time. Commentary between lines or sections would make it easier to use as a cut-n-paste install guide but even a link to this thread would help.

**Comment by zwieblum** [comment]
@mgorges: Without an ```android.keystore``` signing fails because no android.keystore is generated auomaticly:
```
BUILD SUCCESSFUL
Total time: 25 seconds
 => transferring application..
 => zipaligning..
 => removing old /home/nik/.lambdanative/tmp.apk..
 => signing application with keystore /home/nik/.lambdanative/android.keystore
Failed to load signer "signer #1"
java.io.FileNotFoundException: /home/nik/.lambdanative/android.keystore (Datei oder Verzeichnis nicht gefunden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadKeyStoreFromFile(ApkSignerTool.java:832)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:723)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:663)
	at com.android.apksigner.ApkSignerTool$SignerParams.access$500(ApkSignerTool.java:615)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:269)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
ERROR: failed with exit code 2
BUILD FAILED
```

Generating a keystore file manually:
```
keytool -genkey -v -keystore android.keystore -dname "CN=org.example" -alias "org.example" -keyalg RSA -keysize 2048 -validity 10000 -storetype PKCS12 -storepass "0d687d930b3c0716a00ee4e63c72587a" -keypass "secretpassword"
```
Rerunning ```make`` creates a selfsigned APK without error.

Now I have to figure out how to upload the appt to google store - somehow that changed since I last time I did that in 2020. Does anybody have a walkthrough to this strange adventure game named google play console?

**Comment by kiatoa** [comment]
It was no fault of the script, I was missing ant. Maybe add something like this to your script?

for pkg in git autoconf build-essential libtool libgl1-mesa-dev libfreetype6-dev libasound2-dev netpbm imagemagick ghostscript ps2eps texlive-xetex  libxext-dev ant;do if ! dpkg -l --no-pager --robot $pkg &> /dev/null;then echo "Required package $pkg is not installed, exiting.";exit;fi;done

**Comment by karliwalti** [comment]
I can also confirm that the updates from above also work here in my environment. 

However, expanding to libcrypto, I get issues with openssl (again):

```
=> libcrypto..
 => extracting /home/karliwalti/.cache/lambdanative/packages/openssl-1.1.1t.tar.gz..
 => patching source...
 => applying patches from ../sigatomic.patch
Configuring OpenSSL version 1.1.1t (0x1010114fL) for android-arm
Using os-specific seed configuration
$ANDROID_NDK_HOME is not defined at (eval 10) line 32.
 => compiling source..
  CHOST=armv7a-unknown-linux-android23   PKG_CONFIG_PATH=/home/karliwalti/.cache/lambdanative/android/arm-api23/lib/pkgconfig  
...
 LDFLAGS=-L/home/karliwalti/.cache/lambdanative/android/arm-api23/lib   LD_LIBRARY_PATH=/home/karliwalti/.cache/lambdanative/android/arm-api23/lib   CPPFLAGS=-I/home/karliwalti/.cache/lambdanative/android/arm-api23/include   CC="/home/karliwalti/repo/android-sdk-linux/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi23-clang  -fPIC -DANDROID  -I/home/karliwalti/.cache/lambdanative/android/arm-api23/include -L/home/karliwalti/.cache/lambdanative/android/arm-api23/lib"   CXX="/home/karliwalti/repo/android-sdk-linux/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi23-clang++  -fPIC -DANDROID  -I/home/karliwalti/.cache/lambdanative/android/arm-api23/include -L/home/karliwalti/.cache/lambdanative/android/arm-api23/lib"   AR=/home/karliwalti/repo/android-sdk-linux/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar   RANLIB=/home/karliwalti/repo/android-sdk-linux/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib   gmake -j 9 build_libs
gmake[1]: Entering directory '/home/karliwalti/.lambdanative/tmp_install/openssl-1.1.1t'
gmake[1]: *** No rule to make target 'build_libs'.  Stop.
gmake[1]: Leaving directory '/home/karliwalti/.lambdanative/tmp_install/openssl-1.1.1t'
ERROR: failed with exit code 2
>> gmake -j 9 failed
BUILD FAILED - configure with verbose option for more information
make: *** [Makefile:2: all] Error 1
```

**Comment by zwieblum** [comment]
Your ANDROIDNDK variable in SETUP is not set. Please check SETUP, there should be 2 lines: one for ANDROIDSDK and the second for ANDROIDNDK that look about this:
```
ANDROIDSDK=/home/entwicklung/lambdanative/android-sdk-linux
ANDROIDNDK=/home/entwicklung/lambdanative/android-sdk-linux/ndk/25.2.9519653
```

**Comment by karliwalti** [comment]
It is set. Done by your script:
```
sed 's#^\(ANDROIDSDK\)=.*$#\1='$SDK'#' -i SETUP
sed 's#^\(ANDROIDNDK\)=.*$#\1='$(find $SDK/ndk/* -maxdepth 0 -type d | sort | tail -n1)'#' -i SETUP
```

**Comment by mgorges** [comment]
> It was no fault of the script, I was missing ant. Maybe add something like this to your script?

@kiatoa Having ant installed is being checked for in [targets/android/check-tools#L38](https://github.com/part-cw/lambdanative/blob/master/targets/android/check-tools#L38), so I don't know why that failed for you? I'd rather prompt the user to install it themselves than trying to automatically do this, particularly as it might require sudo operations.

> Without an android.keystore signing fails because no android.keystore is generated auomaticly:

@zwieblum This should be made automatically if the presence test fails or has any issues - can you identify why [targets/android/build-binary#L415](https://github.com/part-cw/lambdanative/blob/master/targets/android/build-binary#L415) doesn't do this for you?

> However, expanding to libcrypto, I get issues with openssl (again):

@karliwalti The problem seems related to [libraries/libcrypto/make.sh#L37](https://github.com/part-cw/lambdanative/blob/master/libraries/libcrypto/make.sh#L37), which I changed in [2411fca](https://github.com/part-cw/lambdanative/commit/2411fca03b4e0741d793521b2d538de2fc2c3f88) but that only moves the problem further down in the script to then fail during configuration - if you can sort it out, please make another issue for this, thanks.

**Comment by karliwalti** [comment]
I can confirm that this solved the issue. thanks @mgorges !
Additional library missing from instuctions:  'libtool-bin'

**Comment by zwieblum** [comment]
@mgorges : the scrip is lost in translation: the test for "error" fales 'cause it's "Fehler" in this localized world. Replace https://github.com/part-cw/lambdanative/blob/52eb91faad193a46719004ef30cc213c2ddd09cb/targets/android/build-binary#L412C1-L413C34 and https://github.com/part-cw/lambdanative/blob/52eb91faad193a46719004ef30cc213c2ddd09cb/targets/android/build-binary#L413C5-L413C5 with this line:

```
if keytool -list -keystore $keystore -alias $SYS_ORGDOMAIN_REVERSE_DOT -storepass "$SYS_ANDROIDPW"; then
```
... then the automatic key generation work independent from localisation.

**Comment by mgorges** [comment]
Thanks @zwieblum - added in 1cf634c

**Comment by kiatoa** [comment]
@mgorges - I agree that not installing the packages from the script is best. The snippet I provided only checks for the package being installed. In my case ant not being installed caused me to have to start over with the script. Checking that all required packages are install early in the process would be a nice thing IMHO.

**Comment by kiatoa** [comment]
It may well have found the missing ant there but at that point I would have either had to hack the script or run from the beginning which would take a long time. The script does not have any logic built in to allow it to run incrementally. Given that I'm suggesting running a check for OS packages before downloading and installing the android sdk. Maybe the most pragmatic and easy solution would be to change the script into two or three stand-alone scripts? Either way it isn't too big a deal, more of a suggestion than a request. 

NOTE: at the beginning of the script it wipes out the needed directories (a good idea for a clean start) which means downloading and redoing all that if a problem is discovered later:

rm -Rf lambdanative ~/.cache/lambdanative ~/.lambdanative
rm -Rf $SDK

**Comment by mgorges** [comment]
Downloading and unpacking the SDK is relatively slow, so I would not recommend that routinely - I assume @zwieblum only included that to show a reproducible approach? LambdaNative itself checks for missing packages before it starts to do any compilation or other expensive operations. We'll eventually integrate the lessons from this issue into the [Getting-Started](https://github.com/part-cw/lambdanative/wiki/Getting-Started) wiki page but this is not a priority for me.

**Comment by zwieblum** [comment]
Well, the problem when starting with something new is that you need a well defined installation procedure, otherwise things get interesting. In this case: one iteration of the whole script takes ~ 15 minutes on my laptop. Even when done 10 times it's less time spent than working through "getting started" and trying to figure out why it does not get you started :)
I would at least put a link to the post with the script on the "getting started" page, as the solution of this issue (no sdk) is not solved when you follow the documentation. And you do not find this thread in the list of open issues so anybody trying to get started will not be able to start ...
